title: Steak Knives and Bagels
author: Jonas Heinke
description: Personal website showcasing projects and skills
baseurl: ""
url: "https://your-domain.com"

# Collections
collections:
  blog:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
  golden_triangle_parts:
    output: false
  essays:
    output: true
    permalink: /essays/:title/
  for_want_of_fuel:
    output: true
    permalink: /for-want-of-fuel/:name/
  thoughts:
    output: true
    permalink: /thoughts/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-katex

katex:
  # Enable KaTeX
  enable: true
  # Enable auto-render extension
  auto_render: true
  # Enable display mode
  display_mode: true

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - docs/
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock